# Site
repository: jfkapica.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jakub Kapica 
title: Computer Science Student
email: jkapica17@gmail.com
# email_title: Email (Email title override)
# phone: phone number
# phone_title: Phone (Phone title override)
website: https://github.com/JFkapica
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  JFkapica
linkedin_username: jakub-kapica-5141671a3

# Additional icon links
#additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/placeholder.png
about_content: | # this will include new lines to allow paragraphs
  Hello there! My name is Jakub and I am eager to welcome you to my website, where you can find a little bit about myself! I would like you to know, that I am not going to treat this as a classical CV, but rather as sort of a bio mixed with a little sneakpeak into my thoughts. You could ask: "why not a blog then?", but since I am not planning on updating here frequently, I thought this way of representation would be the most suiting.
  
  How would I describe myself? Probably not in the best possible way ( ;) ), but I will try anyway. As of now, I am 25 years old and I come from Kwidzyn, Poland. I am a working first-year student of computer science. I see myself as an open mind, full of questions and always ready to learn something new. I find great pleasure in knowledge, both in expanding it and in making use of it. 
  As of my best qualities I would say that I am sociable, . In technical department i provide basic knowledge in <mark>C/C++</mark> and <mark>C#</mark>, all used in projects for the purpose of studies. I understand how <mark>GIT</mark> works and write training tasks using the <mark>github</mark> platform.

#  You can even add paragraphs by using empty lines like this and add anything else [markdown](https://www.markdownguide.org/getting-started#what-is-markdown) supports such as
#    - Lists
#    - Tables
#    - <a href="google.com">Links</a>
#    - Images ![alt text](/images/landscape-trees.jpg "Trees")

content:
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: University of Gdansk
        sub_title: BSc in Computer Science
        caption: 2022 - ongoing
        quote: >
          New, hopeful beginning
        description: | # this will include new lines to allow paragraphs
          Description of qualification
      - layout: top-right
        title: Gdansk University of Technology
        sub_title: Engineer of Electronics and Telecommunications
        caption: 2016 - 2020 (drop out after 5th semester)
        quote: >
          Bad choices and tough life lessons
        description: | # this will include new lines to allow paragraphs
          Description of qualification
  - title: Experience
    layout: list
    content:
      - layout: right
        title: Option One sp. z o.o.
        sub_title: Sony Bravia brand representative
        caption: March 2020 - ongoing
        quote: >
          Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Description of role
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Project name
        link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        link_text: Link Text
        additional_links:
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          Short overview of the project (optional)
        description: | # this will include new lines to allow paragraphs
          Description about the work on/with the project
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      This is where you can write a little more about yourself. You could title this section **Interests** and include some of your other interests.

      Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
